apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: my-ingress
    namespace: test-ingress
spec:
    rules:
    - host: ingress.demo.lab
      http:
          paths:
          - path: /
            backend:
                serviceName: my-service
                servicePort: 8000
