apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-template
  namespace: nginx-example
data:
  index.html.template: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx</title>
        <style>
          body { font-family: sans-serif; background-color: #f0f2f5; color: #333; margin: 50px; }
          h1 { color: #0056b3; }
          p { font-size: 1.1em; }
          b { color: #d9534f; }
        </style>
    </head>
    <body>
        <h1>Hello from Nginx in Kubernetes!</h1>
        <p>My internal IP is <b>${POD_IP}</b></p>
        <p>My worker IP is <b>${NODE_IP}</b></p>
        <p>My POD name is <b>${POD_NAME}</b></p>
        <p>This information is dynamic and changes with each Pod.</p>
    </body>
    </html>
